apiVersion: v1
kind: Service
metadata:
  name: predictive-hdd-api
  namespace: predictive-hdd
spec:
  type: NodePort
  selector:
    app: predictive-hdd-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000